// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4OQVadJlMipE2MSQ3ufk9rfTbCv7LXOw',
    appId: '1:632772989657:web:d9171e511be630c01164c8',
    messagingSenderId: '632772989657',
    projectId: 'firabase-login-10b',
    authDomain: 'firabase-login-10b.firebaseapp.com',
    storageBucket: 'firabase-login-10b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmzRCCnFK_vwCLzLoGByONylM6mprZ-vk',
    appId: '1:632772989657:android:f51b41feccf6ffe21164c8',
    messagingSenderId: '632772989657',
    projectId: 'firabase-login-10b',
    storageBucket: 'firabase-login-10b.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYnBNQWfDaztXohVbpN8LlhnxemqVgpwU',
    appId: '1:632772989657:ios:6bfa23ce733fe3191164c8',
    messagingSenderId: '632772989657',
    projectId: 'firabase-login-10b',
    storageBucket: 'firabase-login-10b.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYnBNQWfDaztXohVbpN8LlhnxemqVgpwU',
    appId: '1:632772989657:ios:6bfa23ce733fe3191164c8',
    messagingSenderId: '632772989657',
    projectId: 'firabase-login-10b',
    storageBucket: 'firabase-login-10b.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4OQVadJlMipE2MSQ3ufk9rfTbCv7LXOw',
    appId: '1:632772989657:web:f9dbc7780d251cb91164c8',
    messagingSenderId: '632772989657',
    projectId: 'firabase-login-10b',
    authDomain: 'firabase-login-10b.firebaseapp.com',
    storageBucket: 'firabase-login-10b.firebasestorage.app',
  );

}